### PR TITLE
add UTF-8 to ASCII converter in Util.php

### PR DESCRIPTION
**Pull request by mikimaine**
There is a problem, sort of, when we deal with Unicode in PHP. There are solutions like using mb_* type of functions. But also it is better to have a Util function that will convert to narrowed ASCII when needed specially for character set and collation that doesn't have utf* character set. This function will help for a broader cases with ORM in the future pull request i will do.

www.phptherightway.com/index.html#php_and_utf8

### CODE REVIEW

**Comment by utopiaio** [comment]
> This function will help for a broader cases with ORM in the future pull request i will do

The-Rock is heavily tied with PG with Geometry (via PostGIS) & Full-Text search. Other db support using The-Rock should live on its own fork instead of putting it all into one repository

**Comment by mikimaine** [comment]
What I’m trying to do is at least make Moedoo class generic by adding abstraction to Db drivers. I have scanned all of the methods in Moedoo (Which I guess is the only place The-Rock deals with Database) and all method can be easily implemented to MySQL without breaking any Backward compatibility. 
For the Geometry We can use: [ Spatial Data Types - Mysql Doc](https://dev.mysql.com/doc/refman/5.7/en/spatial-datatypes.html).
For full text Search we can use: [Fulltext Search Functions - Mysql Doc](https://dev.mysql.com/doc/refman/5.7/en/fulltext-search.html)
Adding MySQL support will also allow as to support Maria DB. This will also support the main idea of The-Rock; making it run on most shared hosting easily .

**Comment by utopiaio** [comment]
Tackling database _inconstancies_ should not be handled with wrappers/abstractions in _one_ place; they should be handled separately. The more _generic_ one tries to become, we'll end-up with
> You wanted a banana but what you got was a gorilla holding the banana and the entire jungle

The-Rock should _only_ focus on PG support and working with `pg_*` functions

**Comment by mikimaine** [comment]
hehe OK.

**Pull request merged**
